<?php

namespace Database\Seeders;

use App\Models\Campaign;
use App\Models\User;
use Illuminate\Database\Seeder;

class CampaignSeeder extends Seeder
{
    public function run(): void
    {
        // Find or create a mentor user to own the campaigns
        $mentor = User::where('role', 'mentor')->first()
            ?? User::where('role', 'admin')->first();

        if (!$mentor) return;

        $campaigns = [
            [
                'campaign_name' => 'BNB - HINDI HEALTHY | 2/28 | LASER, CUST...',
                'status' => 'Off',
                'delivery' => 'Off',
                'results' => 486,
                'result_type' => 'Messaging conversations',
                'cost_per_result' => 14.28,
                'cost_per_result_type' => 'Per Messaging Conv.',
                'budget' => 500.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 6940.69,
                'impressions' => 61351,
                'reach' => 30239,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 633,
                'new_messaging' => 408,
                'purchases' => 32,
                'cost_per_purchase' => 216.90,
                'purchases_conversion_value' => 11119.00,
                'purchase_roas' => 1.60,
                'cost_per_new_messaging' => 17.01,
                'messaging_conversations' => 486,
                'cost_per_messaging' => 14.28,
                'orders_created' => 31,
                'orders_shipped' => 36,
                'date_range_start' => '2026-02-15',
                'date_range_end' => '2026-03-16',
            ],
            [
                'campaign_name' => 'BNB - MAY SAKIT BATOK | 3/1 | VIDEO, BROAD',
                'status' => 'On',
                'delivery' => 'Active',
                'results' => 312,
                'result_type' => 'Messaging conversations',
                'cost_per_result' => 18.45,
                'cost_per_result_type' => 'Per Messaging Conv.',
                'budget' => 300.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 5752.40,
                'impressions' => 48920,
                'reach' => 25100,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 410,
                'new_messaging' => 295,
                'purchases' => 18,
                'cost_per_purchase' => 319.58,
                'purchases_conversion_value' => 7250.00,
                'purchase_roas' => 1.26,
                'cost_per_new_messaging' => 19.50,
                'messaging_conversations' => 312,
                'cost_per_messaging' => 18.45,
                'orders_created' => 17,
                'orders_shipped' => 20,
                'date_range_start' => '2026-03-01',
                'date_range_end' => '2026-03-16',
            ],
            [
                'campaign_name' => 'BNB - PROMO MARCH | 3/5 | CAROUSEL, LAL',
                'status' => 'On',
                'delivery' => 'Active',
                'results' => 189,
                'result_type' => 'Meta Purchases',
                'cost_per_result' => 52.30,
                'cost_per_result_type' => 'Per Meta Purchase',
                'budget' => 800.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 9884.70,
                'impressions' => 92450,
                'reach' => 51200,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 220,
                'new_messaging' => 150,
                'purchases' => 189,
                'cost_per_purchase' => 52.30,
                'purchases_conversion_value' => 45800.00,
                'purchase_roas' => 4.63,
                'cost_per_new_messaging' => 65.90,
                'messaging_conversations' => 180,
                'cost_per_messaging' => 54.92,
                'orders_created' => 185,
                'orders_shipped' => 170,
                'date_range_start' => '2026-03-05',
                'date_range_end' => '2026-03-16',
            ],
            [
                'campaign_name' => 'BNB - SKINCARE SET | 2/20 | IMAGE, INTEREST',
                'status' => 'Off',
                'delivery' => 'Off',
                'results' => 45,
                'result_type' => 'Meta Purchases',
                'cost_per_result' => 155.20,
                'cost_per_result_type' => 'Per Meta Purchase',
                'budget' => 400.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 6984.00,
                'impressions' => 35600,
                'reach' => 18900,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 88,
                'new_messaging' => 60,
                'purchases' => 45,
                'cost_per_purchase' => 155.20,
                'purchases_conversion_value' => 8100.00,
                'purchase_roas' => 1.16,
                'cost_per_new_messaging' => 116.40,
                'messaging_conversations' => 72,
                'cost_per_messaging' => 97.00,
                'orders_created' => 42,
                'orders_shipped' => 38,
                'date_range_start' => '2026-02-20',
                'date_range_end' => '2026-03-10',
            ],
            [
                'campaign_name' => 'BNB - HAIR TREATMENT | 3/10 | REEL, CUSTOM',
                'status' => 'On',
                'delivery' => 'Learning',
                'results' => 28,
                'result_type' => 'Messaging conversations',
                'cost_per_result' => 25.71,
                'cost_per_result_type' => 'Per Messaging Conv.',
                'budget' => 200.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 720.00,
                'impressions' => 8500,
                'reach' => 5200,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 35,
                'new_messaging' => 28,
                'purchases' => null,
                'cost_per_purchase' => null,
                'purchases_conversion_value' => null,
                'purchase_roas' => null,
                'cost_per_new_messaging' => 25.71,
                'messaging_conversations' => 28,
                'cost_per_messaging' => 25.71,
                'orders_created' => null,
                'orders_shipped' => null,
                'date_range_start' => '2026-03-10',
                'date_range_end' => '2026-03-16',
            ],
            // --- High performer: great ROAS, should continue ---
            [
                'campaign_name' => 'BNB - SUMMER SALE | 3/8 | VIDEO, LAL',
                'status' => 'On',
                'delivery' => 'Active',
                'results' => 520,
                'result_type' => 'Meta Purchases',
                'cost_per_result' => 28.50,
                'cost_per_result_type' => 'Per Meta Purchase',
                'budget' => 1000.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 14820.00,
                'impressions' => 125000,
                'reach' => 68000,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 680,
                'new_messaging' => 490,
                'purchases' => 520,
                'cost_per_purchase' => 28.50,
                'purchases_conversion_value' => 98500.00,
                'purchase_roas' => 6.65,
                'cost_per_new_messaging' => 30.24,
                'messaging_conversations' => 610,
                'cost_per_messaging' => 24.30,
                'orders_created' => 510,
                'orders_shipped' => 480,
                'date_range_start' => '2026-03-08',
                'date_range_end' => '2026-03-16',
            ],
            // --- Money burner: high spend, poor ROAS, should stop ---
            [
                'campaign_name' => 'BNB - WHITENING SOAP | 2/25 | IMAGE, BROAD',
                'status' => 'On',
                'delivery' => 'Active',
                'results' => 15,
                'result_type' => 'Meta Purchases',
                'cost_per_result' => 480.00,
                'cost_per_result_type' => 'Per Meta Purchase',
                'budget' => 500.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 7200.00,
                'impressions' => 42000,
                'reach' => 28000,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 45,
                'new_messaging' => 30,
                'purchases' => 15,
                'cost_per_purchase' => 480.00,
                'purchases_conversion_value' => 3200.00,
                'purchase_roas' => 0.44,
                'cost_per_new_messaging' => 240.00,
                'messaging_conversations' => 38,
                'cost_per_messaging' => 189.47,
                'orders_created' => 12,
                'orders_shipped' => 10,
                'date_range_start' => '2026-02-25',
                'date_range_end' => '2026-03-16',
            ],
            // --- New campaign: not enough data yet ---
            [
                'campaign_name' => 'BNB - BODY SCRUB | 3/14 | CAROUSEL, INTEREST',
                'status' => 'On',
                'delivery' => 'Learning',
                'results' => 5,
                'result_type' => 'Messaging conversations',
                'cost_per_result' => 40.00,
                'cost_per_result_type' => 'Per Messaging Conv.',
                'budget' => 300.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 200.00,
                'impressions' => 2800,
                'reach' => 1900,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 7,
                'new_messaging' => 5,
                'purchases' => null,
                'cost_per_purchase' => null,
                'purchases_conversion_value' => null,
                'purchase_roas' => null,
                'cost_per_new_messaging' => 40.00,
                'messaging_conversations' => 5,
                'cost_per_messaging' => 40.00,
                'orders_created' => null,
                'orders_shipped' => null,
                'date_range_start' => '2026-03-14',
                'date_range_end' => '2026-03-16',
            ],
            // --- Messaging-focused: good messaging cost, no purchases tracked ---
            [
                'campaign_name' => 'BNB - ANTI AGING SET | 3/3 | VIDEO, CUSTOM',
                'status' => 'On',
                'delivery' => 'Active',
                'results' => 390,
                'result_type' => 'Messaging conversations',
                'cost_per_result' => 10.50,
                'cost_per_result_type' => 'Per Messaging Conv.',
                'budget' => 250.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 4095.00,
                'impressions' => 55000,
                'reach' => 32000,
                'ends' => 'Ongoing',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Lowest cost',
                'total_messaging' => 480,
                'new_messaging' => 350,
                'purchases' => null,
                'cost_per_purchase' => null,
                'purchases_conversion_value' => null,
                'purchase_roas' => null,
                'cost_per_new_messaging' => 11.70,
                'messaging_conversations' => 390,
                'cost_per_messaging' => 10.50,
                'orders_created' => null,
                'orders_shipped' => null,
                'date_range_start' => '2026-03-03',
                'date_range_end' => '2026-03-16',
            ],
            // --- Ended campaign: turned off, mediocre results ---
            [
                'campaign_name' => 'BNB - LIP TINT PROMO | 2/18 | IMAGE, LAL',
                'status' => 'Off',
                'delivery' => 'Off',
                'results' => 95,
                'result_type' => 'Meta Purchases',
                'cost_per_result' => 88.42,
                'cost_per_result_type' => 'Per Meta Purchase',
                'budget' => 350.00,
                'budget_type' => 'Daily average',
                'amount_spent' => 8400.00,
                'impressions' => 62000,
                'reach' => 35000,
                'ends' => 'Ended Mar 10',
                'attribution_setting' => '7-day click or 1-day view',
                'bid_strategy' => 'Highest volume',
                'total_messaging' => 130,
                'new_messaging' => 95,
                'purchases' => 95,
                'cost_per_purchase' => 88.42,
                'purchases_conversion_value' => 14200.00,
                'purchase_roas' => 1.69,
                'cost_per_new_messaging' => 88.42,
                'messaging_conversations' => 110,
                'cost_per_messaging' => 76.36,
                'orders_created' => 90,
                'orders_shipped' => 85,
                'date_range_start' => '2026-02-18',
                'date_range_end' => '2026-03-10',
            ],
        ];

        foreach ($campaigns as $data) {
            Campaign::create(array_merge($data, ['created_by' => $mentor->id]));
        }
    }
}
